#!/bin/sh

# Cap --------------------------------------
cap_eval_to_inria () {
    echo "Syncing evaluations of " $1 "(Be sure you're in torchcap/save)"
    rsync -vazP $1/evaluations pascal:~/scratch/work/torchcap/save/$1
}

cap_eval_from_inria () {
    echo "Syncing evaluations of " $1 "(Be sure you're in torchcap/save)"
    mkdir -p $1
    rsync -vazP pascal:~/scratch/work/torchcap/save/$1/evaluations $1/
}

cap_to_inria () {
    echo "Syncing folder " $1 "(Be sure you're in torchcap/save)"
    rsync -vazP $1 pascal:~/scratch/work/torchcap/save/
}

cap_from_inria () {
    echo "Syncing folder " $1 "(Be sure you're in torchcap/save)"
    rsync -vazP pascal:~/scratch/work/torchcap/save/$1 .
}

cap_cmp_eval() {
    cd save
    echo "Getting the previously generated captions"
    cap_eval_from_inria $1
    cd ..
    python eval.py -c config/$1.yaml --split test
    echo "Updating the evaluation on inria's servers"
    cd save
    cap_eval_to_inria $1
    cd ..
}

# NMT --------------------------------------
nmt_eval_to_inria () {
    echo "Syncing evaluations of " $1 "(Be sure you're in torchcap/save)"
    rsync -vazP $1/evaluations pascal:~/scratch/work/seq2seq/save/$1
}

nmt_eval_from_inria () {
    echo "Syncing evaluations of " $1 "(Be sure you're in torchcap/save)"
    mkdir -p $1
    rsync -vazP pascal:~/scratch/work/seq2seq/save/$1/evaluations $1/
}
nmt_to_inria () {
    echo "Syncing folder " $1 "(Be sure you're in seq2seq/save)"
    rsync -vazP $1 pascal:~/scratch/work/seq2seq/save/
}

nmt_from_inria () {
    echo "Syncing folder " $1 "(Be sure you're in seq2seq/save)"
    rsync -vazP pascal:~/scratch/work/seq2seq/save/$1 .
}
nmt_cmp_eval() {
    cd save
    echo "Getting the previously generated captions"
    nmt_eval_from_inria $1
    cd ..
    python eval.py -c config/$1.yaml --split test
    echo "Updating the evaluation on inria's servers"
    cd save
    nmt_eval_to_inria $1
    cd ..
}
