#!/bin/sh

jsh() {
if [ `hostname -s` = 'aker' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
    jid=$(echo "$stats" | tac | fzf) &&
    oarsub -C $(echo "$jid" | awk '{print $1}')
else
    echo "Run it on aker\n\n"
    ssh aker
fi
}

jlog() {
if [ `hostname -s` = 'aker' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
    jid=$(echo "$stats" | tac | fzf) &&
    jid=$(echo "$jid" | awk '{print $1}')
    less +GF $HOME/<your_log_dir>/*.$jid.stderr
else
    echo "Run it on aker\n\n"
    ssh aker
fi
}

jkill() {
if [ `hostname -s` = 'aker' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3) &&
    jid=$(echo "$stats" | tac | fzf -m) &&
    oardel $(echo "$jid" | awk '{print $1}' | tr '\n' ' ')
else
    echo "Run it on aker\n\n"
    ssh aker
fi
}

sg(){
    ssh -t aker oarsub -I -d $(pwd) -l \"walltime=$1:0:0\"
}




