#!/bin/sh

killfilter (){
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
     filtered=$(echo $stats | grep $1)
     jids=$(echo ${filtered} | awk '{print $1}' | tr '\n' ' ')
     exec=0
     read "choice?Are you sure you want to cancel ${jids} (y/n) ? "
     case "$choice" in 
      y|Y ) echo Cancelling $jids && exec=1;;
      n|N ) echo "Nothing was cancelled!";;
      * ) echo "invalid";;
     esac
     if [[ $exec == 1 ]]; then
       command="oardel ${jids}"
       eval $command
     fi
 }

jsh() {
if [ `hostname -s` = 'edgar' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
    jid=$(echo "$stats" | tac | fzf) &&
    oarsub -C $(echo "$jid" | awk '{print $1}')
else
    echo "Run it on edgar\n\n"
fi
}

jdir() {
if [ `hostname -s` = 'edgar' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
    jid=$(echo "$stats" | tac | fzf) &&
    jid=$(echo "$jid" | awk '{print $1}')
    dir=$(oarstat -fj $jid | grep stdout_file | awk '{print substr($3, 1, length($3)-6)}')
    echo Jobdir $dir
else
    echo "Run it on edgar"
fi
}


jkill() {
if [ `hostname -s` = 'edgar' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3) &&
    jid=$(echo "$stats" | tac | fzf -m) &&
    oardel $(echo "$jid" | awk '{print $1}' | tr '\n' ' ')
else
    echo "Run it on edgar"
fi
}

sg () {
    EXCLUDE=$(cat $HOME/exclude.gpus)
    echo Excluding $EXCLUDE
    BQ=''
    while getopts 'b' flag; do
        case "${flag}" in
            b) BQ='true' ;;  # Besteffort
            *) error "Unexpected option ${flag}" ;;
        esac
    done
    shift $((OPTIND-1))
    MEM=$1
    if [ $BQ ]; then
        echo "Besteffort interactive job"
        cmd="ssh -t edgar oarsub -I -d $(pwd) -l \"walltime=12:0:0\" -p \"\\\"gpumem > '$MEM' AND $EXCLUDE\\\"\" -t besteffort "
    else
        echo "Default interactive job"
        cmd="ssh -t edgar oarsub -I -d $(pwd) -l \"walltime=12:0:0\" -p \"\\\"gpumem > $MEM AND $EXCLUDE\\\"\""
    fi
    echo Running $cmd
    eval $cmd
}

