#!/bin/sh

setcuda91 () {
  export CUDA_HOME="/opt/cuda"
  export CUDA_libs="$CUDA_HOME/lib64"
  export CUDA_bin="$CUDA_HOME/bin"
  export LD_LIBRARY_PATH="$CUDA_libs:$LD_LIBRARY_PATH"
  export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:$CUDA_HOME/include"
  export C_INCLUDE_PATH="$C_INCLUDE_PATH:$CUDA_HOME/include"
  export PATH="$CUDA_bin:$PATH"
  export CUDNN_LIBRARY=$CUDA_HOME
  export CUDNN_LIB_DIR=$CUDA_libs
  export CUDNN_INCLUDE_DIR="$CUDA_HOME/include"
}

setcuda91
