#!/bin/sh

jsh() {
if [ `hostname -s` = 'edgar' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
    jid=$(echo "$stats" | tac | fzf) &&
    oarsub -C $(echo "$jid" | awk '{print $1}')
else
    echo "Run it on edgar\n\n"
    ssh edgar
fi
}

jlog() {
if [ `hostname -s` = 'edgar' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3 | grep -v '^[0-9]\+\s\+W') &&
    jid=$(echo "$stats" | tac | fzf) &&
    jid=$(echo "$jid" | awk '{print $1}')
    less +GF $HOME/<your_log_dir>/*.$jid.stderr
else
    echo "Run it on edgar\n\n"
    ssh edgar
fi
}

jkill() {
if [ `hostname -s` = 'edgar' ]; then
    local stats jid
    stats=$(oarstat --user=$USER --format 2 | tail -n +3) &&
    jid=$(echo "$stats" | tac | fzf -m) &&
    oardel $(echo "$jid" | awk '{print $1}' | tr '\n' ' ')
else
    echo "Run it on edgar\n\n"
    ssh edgar
fi
}

sg () {
    BQ=''
    while getopts 'b' flag; do
        case "${flag}" in
            b) BQ='true' ;;  # Besteffort
            *) error "Unexpected option ${flag}" ;;
        esac
    done
    shift $((OPTIND-1))
    MEM=$1
    if [ $BQ ]; then
        echo "Besteffort interactive job"
        cmd="ssh -t edgar oarsub -I -d $(pwd) -l \"walltime=12:0:0\" -p \"\\\"gpumem > $MEM\\\"\" -t besteffort "
    else
        echo "Default interactive job"
        cmd="ssh -t edgar oarsub -I -d $(pwd) -l \"walltime=12:0:0\" -p \"\\\"gpumem > $MEM\\\"\""
    fi
    eval $cmd
}

